// <auto-generated />
using System;
using Funcy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Funcy.Data.Migrations
{
    [DbContext(typeof(FunctionAppDbContext))]
    [Migration("20260427202308_AddSubscriptionSettings")]
    partial class AddSubscriptionSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Funcy.Data.Entities.Function", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FunctionAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionAppId");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FunctionApps");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionAppSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FunctionAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FunctionAppId");

                    b.ToTable("FunctionAppSlots");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionAppTag", b =>
                {
                    b.Property<long>("FunctionAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FunctionAppId", "Key");

                    b.ToTable("FunctionAppTags");
                });

            modelBuilder.Entity("Funcy.Data.Entities.SubscriptionSetting", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionSettings");
                });

            modelBuilder.Entity("Funcy.Data.Entities.Function", b =>
                {
                    b.HasOne("Funcy.Data.Entities.FunctionApp", "FunctionApp")
                        .WithMany("Functions")
                        .HasForeignKey("FunctionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionApp");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionAppSlot", b =>
                {
                    b.HasOne("Funcy.Data.Entities.FunctionApp", "FunctionApp")
                        .WithMany("Slots")
                        .HasForeignKey("FunctionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionApp");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionAppTag", b =>
                {
                    b.HasOne("Funcy.Data.Entities.FunctionApp", "FunctionApp")
                        .WithMany("Tags")
                        .HasForeignKey("FunctionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionApp");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionApp", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("Slots");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
